export const VN_FIELD = Object.freeze({
  //common user
  id: 'ID',
  name: 'tên',
  email: 'email',
  password: 'mật khẩu',
  phone: 'số điện thoại',
  gender: 'giới tính',
  address: 'địa chỉ',
  dayOfBirth: 'ngày sinh',
  avatar: 'ảnh đại diện',
  refreshToken: 'mã làm mới',
  roleId: 'ID vai trò',
  isEmailVerified: 'tình trạng xác thực email',
  note: 'ghi chú',
  createdAt: 'tạo lúc',
  updatedAt: 'cập nhật lúc',
  deletedAt: 'xóa lúc',
  isActive: 'tình trạng hoạt động',
  //class
  grade: 'khối',
  section: 'phân lớp',
  year: 'năm',
  description: 'mô tả',
  feePerLesson: 'học phí mỗi buổi',
  status: 'trạng thái',
  max_student: 'số học sinh tối đa',
  room: 'phòng học',
  schedule: 'thời khóa biểu',
  scheduleStart_date: 'ngày bắt đầu',
  scheduleEnd_date: 'ngày kết thúc',
  scheduleDays_of_week: 'ngày trong tuần',
  scheduleTime_slotsStart_time: 'thời gian bắt đầu',
  scheduleTime_slotsEnd_time: 'thời gian kết thúc',
  teacher: 'giáo viên',
  // registration
  processed: 'tình trạng xử lý',
  classId: 'ID lớp',
  // teacher
  qualifications: 'trình độ chuyên môn',
  specializations: 'chuyên ngành',
  salaryPerLesson: 'lương mỗi buổi',
  introduction: 'giới thiệu',
  workExperience: 'kinh nghiệm làm việc',
  //student
  parentId: 'ID phụ huynh',
  //class_student
  studentId: 'ID học sinh',
  discountPercent: 'giảm giá (%)',
  //payments
  month: 'tháng',
  totalLessons: 'tổng số buổi học',
  paidAmount: 'số tiền đã thanh toán',
  totalAmount: 'tổng số tiền',
  histories: 'lịch sử',
  teacherId: 'ID giáo viên',
  classes: 'các lớp học',
  // transaction
  amount: 'số tiền',
  transactionAt: 'thời gian giao dịch',
  categoryId: 'ID danh mục',
  //transaction_category
  categoryType: 'loại',
  categoryName: 'tên',
  type: 'loại',
  //menu
  title: 'tiêu đề',
  slug: 'đường dẫn',
  order: 'thứ tự',
  //audit_log
  userId: 'ID người dùng',
  userName: 'tên người dùng',
  userEmail: 'email người dùng',
  userRole: 'vai trò người dùng',
  entityName: 'tên thực thể',
  entityId: 'ID thực thể',
  path: 'đường dẫn',
  method: 'phương thức',
  changedFields: 'trường đã thay đổi',
  oldValue: 'giá trị cũ',
  newValue: 'giá trị mới',
  action: 'hành động',
  //advertisement
  imageUrl: 'đường dẫn ảnh',
  priority: 'độ ưu tiên',
});

export const VN_ACTION = Object.freeze({
  CREATE: 'tạo',
  UPDATE: 'cập nhật',
  DELETE: 'xóa',
});

export const VN_ENTITY = Object.freeze({
  ClassEntity: 'lớp',
  StudentEntity: 'học sinh',
  TeacherEntity: 'giáo viên',
  MenuEntity: 'menu',
  ParentEntity: 'phụ huynh',
  UserEntity: 'người dùng',
  PaymentEntity: 'tài chính học sinh',
  TeacherPaymentEntity: 'tài chính giáo viên',
  RegistrationEntity: 'form đăng ký',
  AdvertisementEntity: 'quảng cáo',
  TransactionEntity: 'thu chi khác',
  TransactionCategoryEntity: 'danh mục thu chi',
});
