export const logMapper = Object.freeze({
  //common user
  id: 'ID',
  name: 'Tên',
  email: 'Email',
  password: 'Mật khẩu',
  phone: 'Số điện thoại',
  gender: 'Giới tính',
  address: 'Địa chỉ',
  dayOfBirth: 'Ngày sinh',
  avatar: 'Ảnh đại diện',
  refreshToken: 'Mã làm mới',
  roleId: 'ID vai trò',
  isEmailVerified: 'Tình trạng xác thực email',
  note: 'Ghi chú',
  createdAt: 'Tạo lúc',
  updatedAt: 'Cập nhật lúc',
  deletedAt: 'Xóa lúc',
  isActive: 'Tình trạng hoạt động',
  //class
  grade: 'Khối',
  section: 'Phân lớp',
  year: 'Năm',
  description: 'Mô tả',
  feePerLesson: 'Học phí mỗi buổi',
  status: 'Trạng thái',
  max_student: 'Số học sinh tối đa',
  room: 'Phòng học',
  schedule: 'Thời khóa biểu',
  scheduleStart_date: 'Ngày bắt đầu',
  scheduleEnd_date: 'Ngày kết thúc',
  scheduleDays_of_week: 'Ngày trong tuần',
  scheduleTimeSlotsStart_time: 'Thời gian bắt đầu',
  scheduleTimeSlotsEnd_time: 'Thời gian kết thúc',
  teacher: 'Giáo viên',
  // registration
  processed: 'Tình trạng xử lý',
  classId: 'ID lớp',
  // teacher
  qualifications: 'Trình độ chuyên môn',
  specializations: 'Chuyên ngành',
  salaryPerLesson: 'Lương mỗi buổi',
  introduction: 'Giới thiệu',
  workExperience: 'Kinh nghiệm làm việc',
  //student
  parentId: 'ID phụ huynh',
  //class_student
  studentId: 'ID học sinh',
  discount_percent: 'Giảm giá (%)',
  //payments
  month: 'Tháng',
  totalLessons: 'Tổng số buổi học',
  paidAmount: 'Số tiền đã thanh toán',
  totalAmount: 'Tổng số tiền',
  discountPercent: 'Giảm giá (%)',
  histories: 'Lịch sử',
  // transaction
  amount: 'Số tiền',
  transaction_at: 'Thời gian giao dịch',
  category_id: 'ID danh mục',
  //transaction_category
  type: 'Loại',
  //menu
  title: 'Tiêu đề',
  slug: 'Đường dẫn',
  order: 'Thứ tự',
  //audit_log
  userId: 'ID người dùng',
  userName: 'Tên người dùng',
  userEmail: 'Email người dùng',
  userRole: 'Vai trò người dùng',
  entityName: 'Tên thực thể',
  entityId: 'ID thực thể',
  path: 'Đường dẫn',
  method: 'Phương thức',
  changedFields: 'Trường đã thay đổi',
  oldValue: 'Giá trị cũ',
  newValue: 'Giá trị mới',
  action: 'Hành động',
});
