export const data = [
    {
        name: "Nguyễn Thị Hoa",
        email: "teacher01@tmix.edu.vn",
        password: "password123",
        role: "teacher",
        dayOfBirth: "05/12/1985",
        phone: "0987654001",
        address: "45 Trần Phú, Quận Ba Đình, Hà Nội",
        gender: "female",
        isActive: true,
        salaryPerLesson: 200000,
        qualifications: ["Bachelor of Education", "TESOL Certificate"],
        specialization: ["IELTS", "General English"],
        description: "Giáo viên dày dặn kinh nghiệm với hơn 10 năm giảng dạy tiếng Anh. Chuyên luyện thi IELTS và phát triển kỹ năng giao tiếp cho học sinh cấp 2, cấp 3."
    },
    {
        name: "Hoàng Văn Phúc",
        email: "teacher02@tmix.edu.vn",
        password: "password123",
        role: "teacher",
        dayOfBirth: "08/23/1988",
        phone: "0987654002",
        address: "78 Nguyễn Huệ, Quận 1, TP.HCM",
        gender: "male",
        isActive: true,
        salaryPerLesson: 250000,
        qualifications: ["Master of Applied Linguistics", "CELTA"],
        specialization: ["IELTS", "TOEIC", "Academic Writing"],
        description: "Thạc sĩ Ngôn ngữ Ứng dụng với chứng chỉ CELTA từ Cambridge. Chuyên đào tạo IELTS Writing & Speaking, đã giúp hàng trăm học sinh đạt band 6.5+."
    },
    {
        name: "Đỗ Thị Lan",
        email: "teacher03@tmix.edu.vn",
        password: "password123",
        role: "teacher",
        dayOfBirth: "03/15/1990",
        phone: "0987654003",
        address: "23 Lê Duẩn, Quận Hải Châu, Đà Nẵng",
        gender: "female",
        isActive: true,
        salaryPerLesson: 180000,
        qualifications: ["Bachelor of English", "TEFL Certificate"],
        specialization: ["General English", "Grammar"],
        description: "Giáo viên trẻ, năng động, tận tâm. Phương pháp giảng dạy hiện đại, kết hợp trò chơi và hoạt động nhóm giúp học sinh hứng thú với tiếng Anh."
    },
    {
        name: "Trần Văn Khoa",
        email: "teacher04@tmix.edu.vn",
        password: "password123",
        role: "teacher",
        dayOfBirth: "11/07/1983",
        phone: "0987654004",
        address: "56 Điện Biên Phủ, Quận Bình Thạnh, TP.HCM",
        gender: "male",
        isActive: true,
        salaryPerLesson: 220000,
        qualifications: ["Master of Education", "TESOL", "IELTS 8.0"],
        specialization: ["TOEFL", "Academic Writing", "Reading"],
        description: "15 năm kinh nghiệm giảng dạy tiếng Anh học thuật. Chuyên gia luyện thi TOEFL và kỹ năng đọc hiểu nâng cao cho học sinh cấp 3."
    },
    {
        name: "Lê Thị Minh",
        email: "teacher05@tmix.edu.vn",
        password: "password123",
        role: "teacher",
        dayOfBirth: "07/20/1992",
        phone: "0987654005",
        address: "34 Nguyễn Trãi, Quận Thanh Xuân, Hà Nội",
        gender: "female",
        isActive: true,
        salaryPerLesson: 180000,
        qualifications: ["Bachelor of Education", "TEFL"],
        specialization: ["Speaking", "Listening", "General English"],
        description: "Chuyên rèn luyện kỹ năng Nói và Nghe cho học sinh. Lớp học tương tác cao, tạo môi trường giao tiếp tiếng Anh tự nhiên."
    },
    {
        name: "Phạm Quang Duy",
        email: "teacher06@tmix.edu.vn",
        password: "password123",
        role: "teacher",
        dayOfBirth: "01/30/1986",
        phone: "0987654006",
        address: "89 Hoàng Văn Thụ, Quận Tân Bình, TP.HCM",
        gender: "male",
        isActive: true,
        salaryPerLesson: 300000,
        qualifications: ["Master of Arts in TESOL", "CELTA", "IELTS 8.5"],
        specialization: ["Business English", "IELTS", "Speaking"],
        description: "Giáo viên cao cấp với bằng Thạc sĩ TESOL từ Đại học Macquarie, Úc. Chuyên đào tạo Business English và luyện thi IELTS band 7.0+."
    },
    {
        name: "Bùi Thị Thảo",
        email: "teacher07@tmix.edu.vn",
        password: "password123",
        role: "teacher",
        dayOfBirth: "09/14/1991",
        phone: "0987654007",
        address: "67 Phan Chu Trinh, TP. Huế, Thừa Thiên Huế",
        gender: "female",
        isActive: true,
        salaryPerLesson: 180000,
        qualifications: ["Bachelor of English Literature", "TEFL"],
        specialization: ["General English", "Vocabulary", "Reading"],
        description: "Giáo viên nhiệt huyết, kiên nhẫn. Giỏi xây dựng từ vựng và kỹ năng đọc hiểu cho học sinh từ cơ bản đến nâng cao."
    },
    {
        name: "Vũ Văn Hùng",
        email: "teacher08@tmix.edu.vn",
        password: "password123",
        role: "teacher",
        dayOfBirth: "04/05/1984",
        phone: "0987654008",
        address: "12 Lạch Tray, Quận Ngô Quyền, Hải Phòng",
        gender: "male",
        isActive: true,
        salaryPerLesson: 200000,
        qualifications: ["Bachelor of Arts", "CELTA", "IELTS 7.5"],
        specialization: ["Business English", "TOEIC", "Grammar"],
        description: "Chuyên gia đào tạo TOEIC và tiếng Anh thương mại. Phương pháp giảng dạy thực tiễn, gắn liền với tình huống thực tế."
    },
    {
        name: "Trần Thị Yến",
        email: "teacher09@tmix.edu.vn",
        password: "password123",
        role: "teacher",
        dayOfBirth: "06/18/1989",
        phone: "0987654009",
        address: "41 Quang Trung, TP. Nha Trang, Khánh Hòa",
        gender: "female",
        isActive: true,
        salaryPerLesson: 200000,
        qualifications: ["Master of Education", "TESOL"],
        specialization: ["IELTS", "Writing", "Speaking"],
        description: "Thạc sĩ Giáo dục với hơn 8 năm kinh nghiệm luyện thi IELTS. Phong cách giảng dạy sáng tạo, hỗ trợ học sinh phát triển toàn diện 4 kỹ năng."
    },
    {
        name: "Nguyễn Văn Bảo",
        email: "teacher10@tmix.edu.vn",
        password: "password123",
        role: "teacher",
        dayOfBirth: "02/11/1987",
        phone: "0987654010",
        address: "25 Nguyễn Chí Thanh, Quận Đống Đa, Hà Nội",
        gender: "male",
        isActive: false,
        salaryPerLesson: 180000,
        qualifications: ["Bachelor of Education", "TESOL"],
        specialization: ["General English", "Grammar"],
        description: "Giáo viên có kinh nghiệm giảng dạy ngữ pháp và tiếng Anh tổng quát. Hiện đang tạm nghỉ."
    }
];